### ISSUE TITLE
dev environment

### ISSUE THREAD

**Issue by chanchn** [pwillia7/austin_graffiti#11]
need to make a readme and establish process on setting up dev env and pushing to master/live server

**Comment by pwillia7** [comment]
Yeah we should use grunt to do all the replacement stuff. After we can get it a little more functional/styled I want to build out a full npm/bower/grunt/Github deployment hook build. We can also setup a staging server when we do that too and work that into the deploy process.

**Comment by pwillia7** [comment]
this - https://www.vagrantup.com/

**Comment by pwillia7** [comment]
So, I think we are pretty good here. We just need a doc that calls out what to do and tells you to CHANGE OWNERSHIP TO www-data. Everything else is pretty easy. reopen if you disagree with this.
